"use client";

import { useEffect, useState } from "react";

type Fix = { lat:number; lng:number; accuracy:number; time:number };
type Log = { id:number; time:string; text:string; lat:number|null; lng:number|null };
const KEY="grace-field-mission-v1";
const shell:React.CSSProperties={background:"#101b16",border:"1px solid #bda775",borderRadius:14,color:"#f4f0e5",padding:14};
const action:React.CSSProperties={background:"#24372c",border:"1px solid #a9976b",borderRadius:10,padding:"12px 10px",color:"#f4f0e5",fontWeight:750,cursor:"pointer"};
function distance(a:Fix,b:{lat:number;lng:number}){const r=Math.PI/180;const dLat=(b.lat-a.lat)*r,dLng=(b.lng-a.lng)*r;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dLng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function bearing(a:Fix,b:{lat:number;lng:number}){const r=Math.PI/180,y=Math.sin((b.lng-a.lng)*r)*Math.cos(b.lat*r),x=Math.cos(a.lat*r)*Math.sin(b.lat*r)-Math.sin(a.lat*r)*Math.cos(b.lat*r)*Math.cos((b.lng-a.lng)*r);return (Math.atan2(y,x)*180/Math.PI+360)%360;}
export default function FieldMission(){
 const [open,setOpen]=useState(false),[fix,setFix]=useState<Fix|null>(null),[gpsError,setGpsError]=useState("Waiting for GPS");
 const [label,setLabel]=useState("Hunting spot"),[lat,setLat]=useState(""),[lng,setLng]=useState(""),[destination,setDestination]=useState<{lat:number;lng:number;name:string}|null>(null);
 const [note,setNote]=useState(""),[logs,setLogs]=useState<Log[]>([]),[started,setStarted]=useState<number|null>(null),[now,setNow]=useState(Date.now()),[message,setMessage]=useState("");
 useEffect(()=>{try{const data=JSON.parse(localStorage.getItem(KEY)||"{}");if(Array.isArray(data.logs))setLogs(data.logs);if(data.destination)setDestination(data.destination);if(typeof data.started==="number")setStarted(data.started);}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem(KEY,JSON.stringify({logs,destination,started}));}catch{setMessage("Storage unavailable; export your records before closing.");}},[logs,destination,started]);
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id);},[]);
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener("grace-field-open-mission",show);return()=>window.removeEventListener("grace-field-open-mission",show);},[]);
 useEffect(()=>{if(!open||!navigator.geolocation)return;const id=navigator.geolocation.watchPosition(p=>{setFix({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,time:p.timestamp});setGpsError("");},e=>setGpsError(e.message),{enableHighAccuracy:true,maximumAge:5000,timeout:20000});return()=>navigator.geolocation.clearWatch(id);},[open]);
 const coord=fix?`${fix.lat.toFixed(6)}, ${fix.lng.toFixed(6)}`:"GPS unavailable";
 const stale=fix?Date.now()-fix.time>60000:true;
 const destinationValid=Number.isFinite(Number(lat))&&Number.isFinite(Number(lng))&&lat.trim()!==""&&lng.trim()!==""&&Math.abs(Number(lat))<=90&&Math.abs(Number(lng))<=180;
 const tripSeconds=started?Math.floor((now-started)/1000):0;
 const tripTime=[Math.floor(tripSeconds/3600),Math.floor(tripSeconds%3600/60),tripSeconds%60].map(x=>String(x).padStart(2,"0")).join(":");
 function saveDestination(){if(!destinationValid){setMessage("Enter valid latitude and longitude.");return;}setDestination({lat:Number(lat),lng:Number(lng),name:label.trim()||"Destination"});setMessage("Destination saved on this device. Bearing is straight-line, not a trail route.");}
 function addLog(){if(!note.trim())return;setLogs(old=>[{id:Date.now(),time:new Date().toISOString(),text:note.trim(),lat:fix?.lat??null,lng:fix?.lng??null},...old]);setNote("");setMessage("Observation saved on this device.");}
 function exportData(){const data={exportedAt:new Date().toISOString(),destination,logs};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="grace-field-records.json";a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function sharePosition(){if(!fix||stale){setMessage("Wait for a fresh GPS fix before sharing.");return;}const text=`Grace Field check-in (${new Date(fix.time).toLocaleString()}): ${coord}. Reported accuracy ±${Math.round(fix.accuracy)} m. https://www.google.com/maps?q=${fix.lat},${fix.lng}`;try{if(navigator.share)await navigator.share({title:"Grace Field check-in",text});else if(navigator.clipboard){await navigator.clipboard.writeText(text);setMessage("Check-in copied. Paste it into a message and SEND it yourself.");}else setMessage("Sharing is not available on this device.");}catch{setMessage("Check-in not sent. Try again or copy your coordinates.");}}
 if(!open)return null;
 return <div style={{position:"fixed",inset:0,zIndex:22000,background:"#000b",display:"flex",alignItems:"flex-end",justifyContent:"center"}}>
  <section style={{...shell,width:"100%",maxWidth:620,maxHeight:"87dvh",overflowY:"auto",borderRadius:"22px 22px 0 0",boxShadow:"0 -12px 50px #000b",fontFamily:"Arial,sans-serif"}}>
   <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><div><div style={{fontSize:10,letterSpacing:2,color:"#cdb780"}}>GRACE FIELD / FIELD OPERATIONS</div><h2 style={{margin:"6px 0 0",fontSize:22}}>Mission Control</h2></div><button style={action} onClick={()=>setOpen(false)}>CLOSE</button></div>
   <p style={{color:"#c7cfc6",fontSize:13}}>Live position, destination bearing, trip timer, observation records and manual check-ins.</p>
   <div style={{...shell,marginBottom:12,background:"#1c2b22"}}><div style={{color:"#cdb780",fontSize:12}}>GPS FIX</div><strong>{coord}</strong><div style={{fontSize:13,marginTop:6}}>{fix?`±${Math.round(fix.accuracy)} meters · ${Math.round((Date.now()-fix.time)/1000)} sec old${stale?" · STALE":""}`:gpsError}</div><button style={{...action,marginTop:10,width:"100%"}} disabled={!fix||stale} onClick={sharePosition}>SHARE MY CURRENT POSITION</button><div style={{fontSize:11,color:"#c7cfc6",marginTop:7}}>Opens your device sharing options. You must select a recipient and send. No automatic monitoring or emergency dispatch.</div></div>
   <div style={{...shell,marginBottom:12}}><div style={{color:"#cdb780",fontWeight:800,marginBottom:10}}>DESTINATION BEARING</div><input aria-label="Destination name" value={label} onChange={e=>setLabel(e.target.value)} placeholder="Destination name" style={{...action,width:"100%",boxSizing:"border-box",marginBottom:8}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><input aria-label="Latitude" inputMode="decimal" value={lat} onChange={e=>setLat(e.target.value)} placeholder="Latitude" style={{...action,width:"100%",boxSizing:"border-box"}}/><input aria-label="Longitude" inputMode="decimal" value={lng} onChange={e=>setLng(e.target.value)} placeholder="Longitude" style={{...action,width:"100%",boxSizing:"border-box"}}/></div><button style={{...action,width:"100%",marginTop:8}} onClick={saveDestination}>SET DESTINATION</button>{destination&&<div style={{marginTop:12}}><strong>{destination.name}</strong><div style={{fontSize:12,color:"#c7cfc6"}}>{destination.lat.toFixed(6)}, {destination.lng.toFixed(6)}</div>{fix&&!stale?<div style={{fontSize:19,color:"#d9c394",marginTop:8}}>{Math.round(bearing(fix,destination))}° · {(distance(fix,destination)/1609.344).toFixed(2)} mi straight-line</div>:<p>Waiting for a fresh GPS fix.</p>}<button style={{...action,marginTop:8}} onClick={()=>setDestination(null)}>CLEAR DESTINATION</button></div>}<p style={{fontSize:11,color:"#c7cfc6"}}>Bearing is relative to true north; compass sensors may need calibration. No obstacle avoidance or turn-by-turn routing.</p></div>
   <div style={{...shell,marginBottom:12}}><div style={{color:"#cdb780",fontWeight:800}}>TRIP CLOCK</div><div style={{fontSize:30,fontVariantNumeric:"tabular-nums",margin:"8px 0"}}>{tripTime}</div><button style={action} onClick={()=>setStarted(started?null:Date.now())}>{started?"STOP / RESET TIMER":"START TIMER"}</button></div>
   <div style={{...shell,marginBottom:12}}><div style={{color:"#cdb780",fontWeight:800,marginBottom:8}}>FIELD OBSERVATIONS · {logs.length}</div><textarea aria-label="Field observation" value={note} onChange={e=>setNote(e.target.value)} placeholder="Tracks, bedding, wind, game sightings, water, hazards..." rows={3} style={{...action,width:"100%",boxSizing:"border-box",resize:"vertical"}}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginTop:8}}><button style={action} onClick={addLog}>SAVE OBSERVATION</button><button style={action} onClick={exportData}>EXPORT RECORDS</button></div>{logs.slice(0,8).map(item=><div key={item.id} style={{borderTop:"1px solid #445447",padding:"10px 0",marginTop:8}}><div style={{fontSize:11,color:"#cdb780"}}>{new Date(item.time).toLocaleString()} {item.lat!==null?`· ${item.lat.toFixed(5)}, ${item.lng?.toFixed(5)}`:""}</div><div style={{whiteSpace:"pre-wrap",marginTop:4}}>{item.text}</div></div>)}</div>
   {message&&<p role="status" style={{color:"#d9c394"}}>{message}</p>}
   <p style={{fontSize:11,color:"#b6c4b8"}}>Records are stored in this browser only. Export a backup. GPS, connectivity and battery can fail; carry a dedicated navigation backup and tell someone your return plan.</p>
  </section>
 </div>;
}
